@startuml
abstract class HandledTransportAction extends TransportAction

abstract class TransportNodesAction extends HandledTransportAction{
    // 可以在指定的多个节点上执行的动作
}

class TransportNodesInfoAction extends TransportNodesAction

abstract class TransportMasterNodeAction extends HandledTransportAction{
    // 必须在master节点上执行的动作
    --
    // 指定执行器名称
    #{abstract} String executor();
    // 检查阻塞情况
    #{abstract} ClusterBlockException checkBlock(Request request, ClusterState state)
    // 在master上执行的操作
    #void masterOperation(...)

}

class TransportCreateIndexAction extends TransportMasterNodeAction{

}

@enduml