@startuml

class TransportService {
    ---
    // 向某个节点发送请求
    +sendRequest(DiscoveryNode node, final String action,TransportRequest, TransportResponseHandler handler)
    // 注册请求处理器, 当接收到其他节点的请求后如何处理。
    +registerRequestHandler(..)
}
@enduml